name: Overwrite some file

on:
  push:
    branches:
      - gh-action-write-json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Fetch posts 
        id: instagram_posts
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "JSON_RESPONSE<<$EOF" >> "$GITHUB_ENV"
          curl --location 'https://graph.instagram.com/6388771287909736/media?fields=id%2Ccaption%2Cmedia_type%2Cmedia_url%2Cthumbnail_url%2Cpermalink&access_token=${IG_TOKEN}'  >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"
        env:
          IG_TOKEN: ${{secrets.VITE_IG_TOKEN}}
      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: "public/test.json"
          write-mode: overwrite
          contents: ${{ steps.instagram_posts.outputs.JSON_RESPONSE }} 
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-action-write-json
          force: true
          message: 'Overwritten by Github Actions - ${date}'
