name: Overwrite some file

on:
  push:
    branches:
      - gh-action-write-json

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_IG_TOKEN: ${{secrets.VITE_IG_TOKEN}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Fetch posts 
        id: instagram_posts
        run: |
          response=$(curl --location https://graph.instagram.com/6388771287909736/media?fields=id%2Ccaption%2Cmedia_type%2Cmedia_url%2Cthumbnail_url%2Cpermalink&access_token=$VITE_IG_TOKEN)
          echo "Response: $response"
          echo "::set-output name=JSON_RESPONSE::$response"
      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: "public/test.json"
          write-mode: overwrite
          contents: ${{steps.instagram_posts.outputs.JSON_RESPONSE}}
        env:
          IG_TOKEN: ${{secrets.VITE_IG_TOKEN}}
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-action-write-json
          force: true
          message: 'Overwritten by Github Actions - ${date}'
